# .platform.app.yaml

# The name of this app. Must be unique within a project.
name: 'dummy'

# The type key specifies the language and version for your application.
type: 'php:7.0'

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            root: ""
            scripts: true
            allow: true

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed. The mount
# path is relative to the application root, where this file lives.
mounts:
    '/web/files': 'shared:files/files'

# The hooks that will be performed when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk, but not access any services like databases.
    build: |
      echo build!!
    # Deploy hooks can access services, but the file system is now read-only.
    deploy: |
      echo deployyyyy

